export const INTERESTS = [
  // ── 1. Travel & Mobility ──────────────────────────────────────────────────
  { title: "Traveling", icon: "airplane-outline" },
  { title: "Solo travel", icon: "person-outline" },
  { title: "Group travel", icon: "people-outline" },
  { title: "Backpacking", icon: "backpack-outline" },
  { title: "Luxury travel", icon: "diamond-outline" },
  { title: "Digital nomad life", icon: "laptop-outline" },
  { title: "Study abroad", icon: "school-outline" },
  { title: "Living abroad", icon: "home-outline" },
  { title: "Relocation planning", icon: "cube-outline" },
  { title: "Visa & immigration tips", icon: "document-text-outline" },
  { title: "Road trips", icon: "car-outline" },
  { title: "Overlanding", icon: "navigate-outline" },
  { title: "Van life", icon: "bus-outline" },
  { title: "Train journeys", icon: "train-outline" },
  { title: "Cruise trips", icon: "boat-outline" },
  { title: "City breaks", icon: "business-outline" },
  { title: "Beach getaways", icon: "sunny-outline" },
  { title: "Safari", icon: "paw-outline" },
  { title: "Cultural tourism", icon: "globe-outline" },
  { title: "Eco-tourism", icon: "leaf-outline" },
  { title: "Volunteer travel", icon: "hand-left-outline" },
  { title: "Pilgrimages", icon: "walk-outline" },

  // ── 2. Adventure & Outdoors ───────────────────────────────────────────────
  { title: "Hiking", icon: "trail-sign-outline" },
  { title: "Trail running", icon: "fitness-outline" },
  { title: "Camping", icon: "bonfire-outline" },
  { title: "Glamping", icon: "star-outline" },
  { title: "Mountaineering", icon: "triangle-outline" },
  { title: "Rock climbing", icon: "arrow-up-outline" },
  { title: "Bouldering", icon: "ellipse-outline" },
  { title: "Caving", icon: "search-outline" },
  { title: "Orienteering", icon: "compass-outline" },
  { title: "Zip-lining", icon: "flash-outline" },
  { title: "Paragliding", icon: "paper-plane-outline" },
  { title: "Skydiving", icon: "cloud-download-outline" },
  { title: "Bungee jumping", icon: "swap-vertical-outline" },
  { title: "Parkour", icon: "body-outline" },
  { title: "Geocaching", icon: "location-outline" },
  { title: "Birdwatching", icon: "eye-outline" },
  { title: "Astrophotography", icon: "telescope-outline" },
  { title: "National parks", icon: "map-outline" },
  { title: "Bushcraft & survival skills", icon: "flame-outline" },

  // ── 3. Food & Drink (Dining Out) ──────────────────────────────────────────
  { title: "Street food", icon: "fast-food-outline" },
  { title: "Fine dining", icon: "restaurant-outline" },
  { title: "Brunch", icon: "cafe-outline" },
  { title: "Steakhouse", icon: "nutrition-outline" },
  { title: "Seafood", icon: "fish-outline" },
  { title: "Vegan & vegetarian restaurants", icon: "leaf-outline" },
  { title: "Food trucks", icon: "car-outline" },
  { title: "Buffets", icon: "grid-outline" },
  { title: "Pop-up dining", icon: "sparkles-outline" },
  { title: "Farmers' markets", icon: "basket-outline" },
  { title: "Food festivals", icon: "ribbon-outline" },
  { title: "Wine bars", icon: "wine-outline" },
  { title: "Cocktail bars", icon: "beer-outline" },
  { title: "Speakeasies", icon: "glasses-outline" },
  { title: "Craft beer pubs", icon: "beer-outline" },
  { title: "Tea houses", icon: "cafe-outline" },
  { title: "Coffee shops", icon: "cafe-outline" },
  { title: "Shisha lounges", icon: "cloud-outline" },

  // ── 4. Cooking & Culinary Arts (At Home) ─────────────────────────────────
  { title: "Home cooking", icon: "restaurant-outline" },
  { title: "Baking", icon: "cube-outline" },
  { title: "Cake decorating", icon: "color-palette-outline" },
  { title: "Grilling & BBQ", icon: "flame-outline" },
  { title: "Smoking meats", icon: "cloud-outline" },
  { title: "Fermentation", icon: "flask-outline" },
  { title: "Pickling", icon: "nutrition-outline" },
  { title: "Sourdough", icon: "ellipse-outline" },
  { title: "Pasta making", icon: "restaurant-outline" },
  { title: "Sushi rolling", icon: "restaurant-outline" },
  { title: "Meal prep", icon: "calendar-outline" },
  { title: "Healthy cooking", icon: "heart-outline" },
  { title: "Keto", icon: "flash-outline" },
  { title: "Paleo", icon: "leaf-outline" },
  { title: "Recipe blogging", icon: "create-outline" },
  { title: "Food photography", icon: "camera-outline" },

  // ── 5. World Cuisines ─────────────────────────────────────────────────────
  { title: "West African cuisine", icon: "globe-outline" },
  { title: "East African cuisine", icon: "globe-outline" },
  { title: "North African cuisine", icon: "globe-outline" },
  { title: "Ethiopian & Eritrean cuisine", icon: "globe-outline" },
  { title: "Caribbean cuisine", icon: "globe-outline" },
  { title: "Afro-Caribbean cuisine", icon: "globe-outline" },
  { title: "Soul food", icon: "globe-outline" },
  { title: "Latin American cuisine", icon: "globe-outline" },
  { title: "Mexican cuisine", icon: "globe-outline" },
  { title: "Peruvian cuisine", icon: "globe-outline" },
  { title: "Brazilian cuisine", icon: "globe-outline" },
  { title: "Mediterranean cuisine", icon: "globe-outline" },
  { title: "Middle Eastern cuisine", icon: "globe-outline" },
  { title: "Turkish cuisine", icon: "globe-outline" },
  { title: "Persian cuisine", icon: "globe-outline" },
  { title: "Indian cuisine", icon: "globe-outline" },
  { title: "Pakistani cuisine", icon: "globe-outline" },
  { title: "Bangladeshi cuisine", icon: "globe-outline" },
  { title: "Sri Lankan cuisine", icon: "globe-outline" },
  { title: "Thai cuisine", icon: "globe-outline" },
  { title: "Vietnamese cuisine", icon: "globe-outline" },
  { title: "Filipino cuisine", icon: "globe-outline" },
  { title: "Indonesian cuisine", icon: "globe-outline" },
  { title: "Chinese regional cuisine", icon: "globe-outline" },
  { title: "Japanese cuisine", icon: "globe-outline" },
  { title: "Korean cuisine", icon: "globe-outline" },
  { title: "Central & Eastern European cuisine", icon: "globe-outline" },
  { title: "Italian cuisine", icon: "globe-outline" },
  { title: "French cuisine", icon: "globe-outline" },
  { title: "Spanish cuisine", icon: "globe-outline" },
  { title: "Portuguese cuisine", icon: "globe-outline" },
  { title: "British cuisine", icon: "globe-outline" },
  { title: "Irish cuisine", icon: "globe-outline" },

  // ── 6. Nightlife & Going Out ──────────────────────────────────────────────
  { title: "Live music gigs", icon: "musical-notes-outline" },
  { title: "Club nights & EDM", icon: "disc-outline" },
  { title: "Salsa, Kizomba & Bachata", icon: "body-outline" },
  { title: "Afrobeats & Amapiano nights", icon: "musical-notes-outline" },
  { title: "Comedy clubs", icon: "happy-outline" },
  { title: "Karaoke", icon: "mic-outline" },
  { title: "Trivia & quiz nights", icon: "help-circle-outline" },
  { title: "Paint & sip", icon: "brush-outline" },
  { title: "Open mic", icon: "mic-outline" },
  { title: "Poetry slams", icon: "book-outline" },
  { title: "Game cafés", icon: "game-controller-outline" },

  // ── 7. Music – Listening (Genres) ─────────────────────────────────────────
  { title: "Afrobeats", icon: "musical-notes-outline" },
  { title: "Amapiano", icon: "musical-notes-outline" },
  { title: "Highlife", icon: "musical-notes-outline" },
  { title: "Fuji & Jùjú music", icon: "musical-notes-outline" },
  { title: "Dancehall", icon: "musical-notes-outline" },
  { title: "Reggae", icon: "musical-notes-outline" },
  { title: "Soca", icon: "musical-notes-outline" },
  { title: "Reggaeton", icon: "musical-notes-outline" },
  { title: "Bachata", icon: "musical-notes-outline" },
  { title: "Salsa", icon: "musical-notes-outline" },
  { title: "Hip-Hop & Rap", icon: "musical-notes-outline" },
  { title: "R&B & Soul", icon: "musical-notes-outline" },
  { title: "Pop", icon: "musical-notes-outline" },
  { title: "K-Pop", icon: "musical-notes-outline" },
  { title: "J-Pop", icon: "musical-notes-outline" },
  { title: "Afro-house & Deep house", icon: "musical-notes-outline" },
  { title: "EDM, Trance & Techno", icon: "musical-notes-outline" },
  { title: "Drum & Bass", icon: "musical-notes-outline" },
  { title: "Jazz", icon: "musical-notes-outline" },
  { title: "Blues", icon: "musical-notes-outline" },
  { title: "Funk", icon: "musical-notes-outline" },
  { title: "Rock", icon: "musical-notes-outline" },
  { title: "Indie & Alt", icon: "musical-notes-outline" },
  { title: "Metal", icon: "musical-notes-outline" },
  { title: "Country", icon: "musical-notes-outline" },
  { title: "Folk", icon: "musical-notes-outline" },
  { title: "Gospel", icon: "musical-notes-outline" },
  { title: "Classical & Opera", icon: "musical-notes-outline" },
  { title: "Soundtracks & Scores", icon: "musical-notes-outline" },
  { title: "Lo-fi & Chillhop", icon: "musical-notes-outline" },

  // ── 8. Music – Making/Participation ──────────────────────────────────────
  { title: "Singing", icon: "mic-outline" },
  { title: "Choir & Gospel choir", icon: "people-outline" },
  { title: "DJing", icon: "disc-outline" },
  { title: "Beatmaking & Production", icon: "equalizer-outline" },
  { title: "Songwriting", icon: "create-outline" },
  { title: "Guitar", icon: "musical-note-outline" },
  { title: "Piano", icon: "musical-note-outline" },
  { title: "Drums", icon: "musical-note-outline" },
  { title: "Strings", icon: "musical-note-outline" },
  { title: "Brass", icon: "musical-note-outline" },
  { title: "Band & Orchestra", icon: "people-outline" },
  { title: "Music theory", icon: "school-outline" },
  { title: "Vinyl collecting", icon: "disc-outline" },
  { title: "Concert photography", icon: "camera-outline" },

  // ── 9. Film, TV & Video ───────────────────────────────────────────────────
  { title: "Movie buff", icon: "film-outline" },
  { title: "Cinema trips", icon: "videocam-outline" },
  { title: "Streaming binges", icon: "tv-outline" },
  { title: "Film festivals", icon: "ribbon-outline" },
  { title: "World cinema", icon: "globe-outline" },
  { title: "Nollywood", icon: "film-outline" },
  { title: "Bollywood", icon: "film-outline" },
  { title: "K-dramas", icon: "tv-outline" },
  { title: "Telenovelas", icon: "tv-outline" },
  { title: "Documentaries", icon: "document-text-outline" },
  { title: "True crime", icon: "search-outline" },
  { title: "Stand-up specials", icon: "happy-outline" },
  { title: "Reality TV", icon: "tv-outline" },
  { title: "Sci-fi & Fantasy", icon: "rocket-outline" },
  { title: "Superhero films", icon: "shield-outline" },
  { title: "Indie films", icon: "film-outline" },
  { title: "Video editing & Videography", icon: "cut-outline" },

  // ── 10. Anime, Comics & Pop Culture ──────────────────────────────────────
  { title: "Anime", icon: "tv-outline" },
  { title: "Manga", icon: "book-outline" },
  { title: "Manhwa", icon: "book-outline" },
  { title: "Cosplay", icon: "shirt-outline" },
  { title: "Conventions", icon: "people-outline" },
  { title: "Graphic novels", icon: "albums-outline" },
  { title: "Superhero fandoms", icon: "shield-outline" },
  { title: "VTubers", icon: "videocam-outline" },

  // ── 11. Books & Reading ───────────────────────────────────────────────────
  { title: "Contemporary fiction", icon: "book-outline" },
  { title: "Classics", icon: "book-outline" },
  { title: "Fantasy", icon: "book-outline" },
  { title: "Sci-fi books", icon: "book-outline" },
  { title: "Romance", icon: "book-outline" },
  { title: "Mystery & Thriller", icon: "book-outline" },
  { title: "Historical fiction", icon: "book-outline" },
  { title: "Poetry", icon: "book-outline" },
  { title: "Memoir & Biography", icon: "book-outline" },
  { title: "Self-help", icon: "book-outline" },
  { title: "Business books", icon: "briefcase-outline" },
  { title: "Psychology books", icon: "book-outline" },
  { title: "Philosophy", icon: "book-outline" },
  { title: "Politics books", icon: "book-outline" },
  { title: "History books", icon: "book-outline" },
  { title: "Religion & faith books", icon: "book-outline" },
  { title: "Travel writing", icon: "book-outline" },
  { title: "Book clubs", icon: "people-outline" },

  // ── 12. Podcasts & Audio ──────────────────────────────────────────────────
  { title: "News podcasts", icon: "newspaper-outline" },
  { title: "Comedy podcasts", icon: "happy-outline" },
  { title: "True crime podcasts", icon: "headset-outline" },
  { title: "Personal development podcasts", icon: "trending-up-outline" },
  { title: "Tech podcasts", icon: "headset-outline" },
  { title: "Business podcasts", icon: "briefcase-outline" },
  { title: "Relationship podcasts", icon: "heart-outline" },
  { title: "Sports podcasts", icon: "headset-outline" },
  { title: "Faith podcasts", icon: "headset-outline" },
  { title: "Language learning podcasts", icon: "language-outline" },
  { title: "Audio dramas", icon: "headset-outline" },

  // ── 13. Sports – Team & Court ─────────────────────────────────────────────
  { title: "Football & Soccer", icon: "football-outline" },
  { title: "Basketball", icon: "basketball-outline" },
  { title: "American football", icon: "american-football-outline" },
  { title: "Baseball & Softball", icon: "baseball-outline" },
  { title: "Rugby", icon: "american-football-outline" },
  { title: "Cricket", icon: "tennisball-outline" },
  { title: "Hockey", icon: "tennisball-outline" },
  { title: "Volleyball", icon: "tennisball-outline" },
  { title: "Handball", icon: "hand-left-outline" },
  { title: "Lacrosse", icon: "tennisball-outline" },
  { title: "Netball", icon: "tennisball-outline" },
  { title: "Futsal", icon: "football-outline" },

  // ── 14. Sports – Racket & Precision ──────────────────────────────────────
  { title: "Tennis", icon: "tennisball-outline" },
  { title: "Table tennis", icon: "tennisball-outline" },
  { title: "Badminton", icon: "tennisball-outline" },
  { title: "Pickleball", icon: "tennisball-outline" },
  { title: "Squash", icon: "tennisball-outline" },
  { title: "Golf", icon: "golf-outline" },
  { title: "Darts", icon: "locate-outline" },
  { title: "Billiards & Pool", icon: "ellipse-outline" },
  { title: "Archery", icon: "arrow-forward-outline" },

  // ── 15. Sports – Water ────────────────────────────────────────────────────
  { title: "Swimming", icon: "water-outline" },
  { title: "Surfing", icon: "water-outline" },
  { title: "Bodyboarding", icon: "water-outline" },
  { title: "Windsurfing", icon: "water-outline" },
  { title: "Kitesurfing", icon: "water-outline" },
  { title: "Paddleboarding", icon: "water-outline" },
  { title: "Kayaking", icon: "boat-outline" },
  { title: "Canoeing", icon: "boat-outline" },
  { title: "Sailing", icon: "boat-outline" },
  { title: "Rowing", icon: "boat-outline" },
  { title: "Scuba diving", icon: "water-outline" },
  { title: "Snorkeling", icon: "water-outline" },
  { title: "Free diving", icon: "water-outline" },
  { title: "Water polo", icon: "water-outline" },

  // ── 16. Sports – Winter & Wheels ─────────────────────────────────────────
  { title: "Skiing", icon: "snow-outline" },
  { title: "Snowboarding", icon: "snow-outline" },
  { title: "Ice skating", icon: "snow-outline" },
  { title: "Rollerblading", icon: "bicycle-outline" },
  { title: "Skateboarding", icon: "bicycle-outline" },
  { title: "BMX", icon: "bicycle-outline" },

  // ── 17. Combat Sports & Martial Arts ─────────────────────────────────────
  { title: "Boxing", icon: "fitness-outline" },
  { title: "Kickboxing", icon: "fitness-outline" },
  { title: "Muay Thai", icon: "fitness-outline" },
  { title: "MMA & UFC", icon: "fitness-outline" },
  { title: "Brazilian Jiu-Jitsu", icon: "fitness-outline" },
  { title: "Judo", icon: "fitness-outline" },
  { title: "Karate", icon: "fitness-outline" },
  { title: "Taekwondo", icon: "fitness-outline" },
  { title: "Capoeira", icon: "body-outline" },
  { title: "Krav Maga", icon: "fitness-outline" },
  { title: "Wrestling", icon: "fitness-outline" },
  { title: "Fencing", icon: "fitness-outline" },

  // ── 18. Fitness & Wellness ────────────────────────────────────────────────
  { title: "Gym & Weightlifting", icon: "barbell-outline" },
  { title: "Calisthenics", icon: "body-outline" },
  { title: "CrossFit & Functional training", icon: "barbell-outline" },
  { title: "HIIT", icon: "flash-outline" },
  { title: "Pilates", icon: "body-outline" },
  { title: "Barre", icon: "body-outline" },
  { title: "Yoga", icon: "body-outline" },
  { title: "Stretching & Mobility", icon: "body-outline" },
  { title: "Zumba & Dance fitness", icon: "musical-notes-outline" },
  { title: "Step goals & Walking", icon: "footsteps-outline" },
  { title: "Fit hiking", icon: "trail-sign-outline" },
  { title: "Cycling", icon: "bicycle-outline" },
  { title: "Fitness challenges", icon: "trophy-outline" },

  // ── 19. Mindset, Mental Health & Spirituality ─────────────────────────────
  { title: "Meditation", icon: "moon-outline" },
  { title: "Breathwork", icon: "cloud-outline" },
  { title: "Journaling", icon: "journal-outline" },
  { title: "Therapy & Coaching", icon: "chatbubbles-outline" },
  { title: "Gratitude practice", icon: "heart-outline" },
  { title: "Stoicism", icon: "library-outline" },
  { title: "Mindfulness retreats", icon: "leaf-outline" },
  { title: "Reiki & Energy work", icon: "hand-right-outline" },
  { title: "Vision boards", icon: "images-outline" },
  { title: "Goal setting", icon: "flag-outline" },

  // ── 20. Art & Design ──────────────────────────────────────────────────────
  { title: "Drawing & Sketching", icon: "pencil-outline" },
  { title: "Painting", icon: "brush-outline" },
  { title: "Calligraphy", icon: "pencil-outline" },
  { title: "Illustration", icon: "color-palette-outline" },
  { title: "Graphic design", icon: "layers-outline" },
  { title: "UX & UI design", icon: "desktop-outline" },
  { title: "Photography", icon: "camera-outline" },
  { title: "Film photography & Darkroom", icon: "camera-outline" },
  { title: "Drone photography", icon: "camera-outline" },
  { title: "Sculpture", icon: "cube-outline" },
  { title: "Printmaking", icon: "print-outline" },
  { title: "Ceramics & Pottery", icon: "ellipse-outline" },
  { title: "Textile art", icon: "cut-outline" },
  { title: "Collage", icon: "albums-outline" },
  { title: "Street art", icon: "brush-outline" },

  // ── 21. Crafts, Maker & DIY ───────────────────────────────────────────────
  { title: "Knitting", icon: "cut-outline" },
  { title: "Crochet", icon: "cut-outline" },
  { title: "Sewing", icon: "cut-outline" },
  { title: "Quilting", icon: "grid-outline" },
  { title: "Embroidery", icon: "color-palette-outline" },
  { title: "Weaving", icon: "grid-outline" },
  { title: "Macramé", icon: "link-outline" },
  { title: "Jewelry making", icon: "diamond-outline" },
  { title: "Candle making", icon: "flame-outline" },
  { title: "Soap making", icon: "water-outline" },
  { title: "Leatherworking", icon: "construct-outline" },
  { title: "Woodworking", icon: "hammer-outline" },
  { title: "Metalworking", icon: "construct-outline" },
  { title: "3D printing", icon: "print-outline" },
  { title: "Model building", icon: "cube-outline" },
  { title: "Origami & Papercraft", icon: "document-outline" },
  { title: "Resin art", icon: "color-palette-outline" },

  // ── 22. Home, Plants & Gardening ─────────────────────────────────────────
  { title: "Houseplants", icon: "leaf-outline" },
  { title: "Succulents", icon: "leaf-outline" },
  { title: "Bonsai", icon: "leaf-outline" },
  { title: "Aquascaping", icon: "water-outline" },
  { title: "Urban gardening", icon: "flower-outline" },
  { title: "Allotment & Backyard farming", icon: "leaf-outline" },
  { title: "Hydroponics", icon: "water-outline" },
  { title: "Landscaping", icon: "image-outline" },
  { title: "Composting", icon: "refresh-outline" },
  { title: "Interior design", icon: "color-palette-outline" },
  { title: "Home organizing", icon: "archive-outline" },
  { title: "Smart home", icon: "wifi-outline" },

  // ── 23. Pets & Animals ────────────────────────────────────────────────────
  { title: "Dogs", icon: "paw-outline" },
  { title: "Cats", icon: "paw-outline" },
  { title: "Birds", icon: "paw-outline" },
  { title: "Fishkeeping & Aquariums", icon: "fish-outline" },
  { title: "Reptiles & Amphibians", icon: "paw-outline" },
  { title: "Small pets", icon: "paw-outline" },
  { title: "Horses & Equestrian", icon: "paw-outline" },
  { title: "Beekeeping", icon: "paw-outline" },
  { title: "Animal rescue & shelters", icon: "heart-outline" },
  { title: "Pet training", icon: "ribbon-outline" },

  // ── 24. Tech & Computing ──────────────────────────────────────────────────
  { title: "Gadgets", icon: "phone-portrait-outline" },
  { title: "PC building", icon: "hardware-chip-outline" },
  { title: "Mechanical keyboards", icon: "keypad-outline" },
  { title: "Coding", icon: "code-slash-outline" },
  { title: "AI & Machine learning", icon: "hardware-chip-outline" },
  { title: "No-code & Low-code", icon: "apps-outline" },
  { title: "Product design", icon: "color-wand-outline" },
  { title: "Cybersecurity", icon: "shield-checkmark-outline" },
  { title: "Ethical hacking", icon: "terminal-outline" },
  { title: "DevOps & Cloud", icon: "cloud-outline" },
  { title: "Robotics", icon: "hardware-chip-outline" },
  { title: "Electronics & Arduino", icon: "flash-outline" },
  { title: "3D modeling & CAD", icon: "cube-outline" },
  { title: "XR, VR & AR", icon: "glasses-outline" },

  // ── 25. Science & Learning ────────────────────────────────────────────────
  { title: "Astronomy", icon: "telescope-outline" },
  { title: "Space exploration", icon: "rocket-outline" },
  { title: "Physics", icon: "nuclear-outline" },
  { title: "Chemistry", icon: "flask-outline" },
  { title: "Biology", icon: "leaf-outline" },
  { title: "Geology", icon: "diamond-outline" },
  { title: "Oceanography", icon: "water-outline" },
  { title: "Math", icon: "calculator-outline" },
  { title: "Psychology", icon: "brain-outline" },
  { title: "Neuroscience", icon: "brain-outline" },
  { title: "Anthropology", icon: "people-outline" },
  { title: "Linguistics", icon: "language-outline" },
  { title: "History", icon: "time-outline" },
  { title: "Geography", icon: "map-outline" },
  { title: "Geopolitics", icon: "globe-outline" },
  { title: "Economics", icon: "trending-up-outline" },
  { title: "Education & EdTech", icon: "school-outline" },
  { title: "Academic research", icon: "search-outline" },
  { title: "Museums", icon: "business-outline" },

  // ── 26. Business, Money & Work ────────────────────────────────────────────
  { title: "Entrepreneurship & Startups", icon: "rocket-outline" },
  { title: "Freelancing", icon: "laptop-outline" },
  { title: "Side hustles", icon: "bulb-outline" },
  { title: "Investing & Stocks", icon: "trending-up-outline" },
  { title: "Crypto & Web3", icon: "logo-bitcoin" },
  { title: "Real estate", icon: "home-outline" },
  { title: "Personal finance", icon: "wallet-outline" },
  { title: "Career growth", icon: "arrow-up-outline" },
  { title: "Networking", icon: "people-outline" },
  { title: "Public speaking", icon: "megaphone-outline" },
  { title: "Negotiation", icon: "chatbubbles-outline" },
  { title: "Branding & Marketing", icon: "megaphone-outline" },
  { title: "Sales", icon: "cash-outline" },

  // ── 27. Fashion & Beauty ──────────────────────────────────────────────────
  { title: "Streetwear", icon: "shirt-outline" },
  { title: "Vintage & Thrifting", icon: "bag-handle-outline" },
  { title: "Sneaker culture", icon: "footsteps-outline" },
  { title: "Haute couture", icon: "diamond-outline" },
  { title: "Tailoring", icon: "cut-outline" },
  { title: "Modest fashion", icon: "shirt-outline" },
  { title: "Cultural & traditional fashion", icon: "shirt-outline" },
  { title: "Makeup artistry", icon: "color-palette-outline" },
  { title: "Skincare", icon: "sparkles-outline" },
  { title: "Haircare, Braids & Locs", icon: "person-outline" },
  { title: "Nails & Nail art", icon: "sparkles-outline" },
  { title: "Fragrance & Perfumery", icon: "rose-outline" },
  { title: "Jewelry & Style inspo", icon: "diamond-outline" },

  // ── 28. Cars, Bikes & Motors ──────────────────────────────────────────────
  { title: "Car meets", icon: "car-sport-outline" },
  { title: "Car detailing & Tuning", icon: "construct-outline" },
  { title: "JDM", icon: "car-outline" },
  { title: "Euro cars", icon: "car-outline" },
  { title: "Muscle cars", icon: "car-outline" },
  { title: "Overlanding & 4×4", icon: "navigate-outline" },
  { title: "Formula 1", icon: "flag-outline" },
  { title: "Motorcycles", icon: "bicycle-outline" },
  { title: "Scooters", icon: "bicycle-outline" },
  { title: "E-bikes", icon: "bicycle-outline" },
  { title: "Cycling commuting", icon: "bicycle-outline" },
  { title: "Karting", icon: "flag-outline" },
  { title: "Sim racing", icon: "game-controller-outline" },

  // ── 29. Collecting ────────────────────────────────────────────────────────
  { title: "Sneaker collecting", icon: "footsteps-outline" },
  { title: "Watch collecting", icon: "watch-outline" },
  { title: "Vinyl records", icon: "disc-outline" },
  { title: "CDs & Cassettes", icon: "disc-outline" },
  { title: "Comic books", icon: "book-outline" },
  { title: "Trading cards", icon: "id-card-outline" },
  { title: "Coin collecting", icon: "cash-outline" },
  { title: "Stamp collecting", icon: "mail-outline" },
  { title: "Antiques", icon: "time-outline" },
  { title: "Vintage cameras", icon: "camera-outline" },
  { title: "Figurines & Models", icon: "cube-outline" },
  { title: "Art prints", icon: "image-outline" },
  { title: "NFTs", icon: "grid-outline" },

  // ── 30. Games – Video & Tabletop ──────────────────────────────────────────
  { title: "Console gaming", icon: "game-controller-outline" },
  { title: "PC gaming", icon: "game-controller-outline" },
  { title: "Mobile gaming", icon: "phone-portrait-outline" },
  { title: "Retro gaming", icon: "game-controller-outline" },
  { title: "Strategy games", icon: "chess-outline" },
  { title: "FPS games", icon: "game-controller-outline" },
  { title: "MOBA", icon: "game-controller-outline" },
  { title: "Battle royale", icon: "game-controller-outline" },
  { title: "RPG & JRPG", icon: "game-controller-outline" },
  { title: "4X & Grand strategy", icon: "map-outline" },
  { title: "Simulation games", icon: "desktop-outline" },
  { title: "Sports video games", icon: "football-outline" },
  { title: "Rhythm games", icon: "musical-notes-outline" },
  { title: "Board games", icon: "grid-outline" },
  { title: "Party games", icon: "happy-outline" },
  { title: "Card games", icon: "card-outline" },
  { title: "Chess & Go", icon: "grid-outline" },
  { title: "Tabletop RPG (D&D)", icon: "dice-outline" },

  // ── 31. Culture, Identity & Diaspora ─────────────────────────────────────
  { title: "Ancestry & Genealogy", icon: "git-branch-outline" },
  { title: "Mother tongue learning", icon: "language-outline" },
  { title: "Code-switching", icon: "swap-horizontal-outline" },
  { title: "Cultural etiquette", icon: "handshake-outline" },
  { title: "Traditional music & dance", icon: "musical-notes-outline" },
  { title: "Cultural festivals", icon: "ribbon-outline" },
  { title: "Diaspora communities", icon: "people-circle-outline" },
  { title: "Pan-Africanism", icon: "globe-outline" },
  { title: "Afro-Latinidad", icon: "globe-outline" },
  { title: "Black history", icon: "time-outline" },
  { title: "Indigenous cultures", icon: "leaf-outline" },
  { title: "Intercultural relationships", icon: "heart-outline" },

  // ── 32. Faith & Worship ───────────────────────────────────────────────────
  { title: "Christianity", icon: "cross-outline" },
  { title: "Islam", icon: "moon-outline" },
  { title: "Judaism", icon: "star-outline" },
  { title: "Hinduism", icon: "flower-outline" },
  { title: "Buddhism", icon: "leaf-outline" },
  { title: "Sikhism", icon: "flower-outline" },
  { title: "Traditional African religions", icon: "musical-notes-outline" },
  { title: "Interfaith dialogue", icon: "chatbubbles-outline" },
  { title: "Pilgrimages & Sacred travel", icon: "map-outline" },
  { title: "Fasting seasons", icon: "moon-outline" },

  // ── 33. Social Impact & Volunteering ─────────────────────────────────────
  { title: "Community organizing", icon: "people-outline" },
  { title: "Youth mentorship", icon: "person-add-outline" },
  { title: "Education access", icon: "school-outline" },
  { title: "Refugee support", icon: "hand-left-outline" },
  { title: "Immigration advocacy", icon: "globe-outline" },
  { title: "Voter engagement", icon: "ballot-outline" },
  { title: "Human rights", icon: "hand-right-outline" },
  { title: "DEI", icon: "people-outline" },
  { title: "Anti-racism", icon: "hand-left-outline" },
  { title: "Women's empowerment", icon: "female-outline" },
  { title: "LGBTQ+ advocacy", icon: "rainbow-outline" },
  { title: "Environmentalism", icon: "leaf-outline" },
  { title: "Beach & park cleanups", icon: "trash-bin-outline" },
  { title: "Animal welfare", icon: "paw-outline" },

  // ── 34. Humor, Media & Creator Life ──────────────────────────────────────
  { title: "Memes", icon: "happy-outline" },
  { title: "TikTok & Reels", icon: "phone-portrait-outline" },
  { title: "Content creation", icon: "videocam-outline" },
  { title: "Vlogging", icon: "camera-outline" },
  { title: "Livestreaming", icon: "radio-outline" },
  { title: "Podcasting", icon: "mic-outline" },
  { title: "Shorts & Reels", icon: "film-outline" },
  { title: "ASMR", icon: "headset-outline" },
  { title: "Voice acting", icon: "mic-outline" },
  { title: "Graphic memes", icon: "image-outline" },
  { title: "Fan edits", icon: "cut-outline" },
  { title: "Influencer marketing", icon: "megaphone-outline" },

  // ── 35. Long-Distance Love & Cross-Border Life ────────────────────────────
  { title: "Time-zone romance hacks", icon: "time-outline" },
  { title: "Virtual date nights", icon: "videocam-outline" },
  { title: "Watch parties", icon: "tv-outline" },
  { title: "Online co-op games", icon: "game-controller-outline" },
  { title: "Shared playlists", icon: "musical-notes-outline" },
  { title: "Shared fitness challenges", icon: "fitness-outline" },
  { title: "Language exchange with partner", icon: "language-outline" },
  { title: "Care packages & Gifts", icon: "gift-outline" },
  { title: "Travel planning together", icon: "airplane-outline" },
  { title: "Budgeting across currencies", icon: "wallet-outline" },
  { title: "Visa & immigration research", icon: "document-text-outline" },
  { title: "Relocation for love", icon: "heart-outline" },
  { title: "Meeting the family remotely", icon: "people-outline" },
  { title: "Cultural etiquette for in-laws", icon: "handshake-outline" },
  { title: "Photo journaling", icon: "images-outline" },
  { title: "Pen-pal letters", icon: "mail-outline" },

  // ── 36. Education & Student Life ─────────────────────────────────────────
  { title: "Study groups", icon: "people-outline" },
  { title: "Campus societies", icon: "school-outline" },
  { title: "Debating", icon: "chatbubbles-outline" },
  { title: "Model UN", icon: "globe-outline" },
  { title: "Hackathons", icon: "code-slash-outline" },
  { title: "Research labs", icon: "flask-outline" },
  { title: "Exchange programs", icon: "airplane-outline" },
  { title: "Scholarships hunt", icon: "trophy-outline" },
  { title: "Grad school applications", icon: "school-outline" },

  // ── 37. Seasonal & Holidays ───────────────────────────────────────────────
  { title: "Christmas markets", icon: "gift-outline" },
  { title: "Easter", icon: "flower-outline" },
  { title: "Eid", icon: "moon-outline" },
  { title: "Diwali", icon: "flame-outline" },
  { title: "Holi", icon: "color-palette-outline" },
  { title: "Hanukkah", icon: "flame-outline" },
  { title: "Lunar New Year", icon: "star-outline" },
  { title: "Thanksgiving", icon: "basket-outline" },
  { title: "Halloween", icon: "skull-outline" },
  { title: "Oktoberfest", icon: "beer-outline" },
  { title: "Carnival", icon: "ribbon-outline" },
  { title: "Day of the Dead", icon: "skull-outline" },
  { title: "Independence Day", icon: "flag-outline" },
  { title: "Eid al-Adha", icon: "moon-outline" },
  { title: "New Year's", icon: "sparkles-outline" },
  { title: "Summer festivals", icon: "sunny-outline" },

  // ── 38. Community & Events ────────────────────────────────────────────────
  { title: "Networking events", icon: "people-circle-outline" },
  { title: "Conferences & Meetups", icon: "megaphone-outline" },
  { title: "Tech meetups", icon: "hardware-chip-outline" },
  { title: "Book clubs", icon: "book-outline" },
  { title: "Running clubs", icon: "fitness-outline" },
  { title: "Cycling groups", icon: "bicycle-outline" },
  { title: "Hiking clubs", icon: "trail-sign-outline" },
  { title: "Faith groups", icon: "heart-outline" },
  { title: "Diaspora mixers", icon: "globe-outline" },
  { title: "Language meetups", icon: "language-outline" },
  { title: "Dance socials", icon: "musical-notes-outline" },
  { title: "Charity galas", icon: "ribbon-outline" },
] as const;

export const GENDERS = ["women", "man", "nonbinary"] as const;
