export const INTERESTS = [
  { title: "Travelling", icon: "airplane-outline" },
  { title: "Photography", icon: "camera-outline" },
  { title: "Art", icon: "color-palette-outline" },
  { title: "Painting", icon: "brush-outline" },
  { title: "Yoga", icon: "body-outline" },
  { title: "Dancing", icon: "musical-notes-outline" },
  { title: "Movie", icon: "film-outline" },
  { title: "Tennis", icon: "tennisball-outline" },
  { title: "Soccer", icon: "football-outline" },
  { title: "Basketball", icon: "basketball-outline" },
  { title: "Ambition", icon: "star-outline" },
  { title: "Writing", icon: "create-outline" },
  { title: "Grab a drink", icon: "beer-outline" },
  { title: "Astrology", icon: "planet-outline" },
  { title: "Running", icon: "walk-outline" },
  { title: "Game", icon: "game-controller-outline" },
  { title: "Hiking", icon: "trail-sign-outline" },
  { title: "Walking", icon: "footsteps-outline" },
  { title: "Surfing", icon: "boat-outline" },
  { title: "Swimming", icon: "water-outline" },
  { title: "Singing", icon: "mic-outline" },
  { title: "Confidence", icon: "shield-checkmark-outline" },
] as const;

export const GENDERS = ["women", "man", "nonbinary"] as const;
